version: "3.9"

services:
  keycloak:
    image: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8
    platform: linux/amd64
    container_name: redhat-sso
    environment:
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin
      SSO_REALM: b2c-poc
    ports:
      - "8080:8080"
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=MinhaEmpresa
      - LDAP_DOMAIN=empresa.local
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
